# This is a basic workflow to help you get started with Actions

name: CI

version: 2.0

jobs:
  run:
    name: Build and publish docker images
    runs-on: ubuntu-latest
    steps:
    
   auth:
    username: ineomail
    password: $DOCKERHUB_PASSWORD
  
    steps:
        - checkout
      
  - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            app_version=${{ env.VERSION }}
            release_date=${{ env.RELEASE_DATE }}
 
